# -----------------------------------
planner: 
  type: 5        #0->lissajous 1->circle 2->clickedPose 3->spiral 4->StepResponse 5->primitive planner
  pause: false
  iterations: 3
  reference:  [1. , 1. , 0, 0 ,0 ,0 ]    #X Y Z R P Y
  
  growth: 0.33 
  r0: 3

  omega: 0.2
  ratio: 1
  phaseshift: 1.5708
  amplifier_x: 3.0
  amplifier_y: 3.0

  step_sizes: [1.0, 1.0, 0.5]  # x [m] y[m] phi[times pi] -> [1.0 1.0 0.5] means 1m in x 1m in y and 0.5pi in phi
  delay: 6.0


#Names of formation memebers for parsing the formation parameters
formation:
  # names: ["master","robot1","robot2","robot3","robot4"] #Names of the robots belonging to one formation
  names: ["master","robot1","robot2","robot3"] #Names of the robots belonging to one formation

# Remaped, shared parameter for all the robots
controller_type: 2                        # 1-> pseudo_invers 2->lyapov 3->angl_dist
lyapunov: [7.0,12.0,1.0]                   # parameter for lyapunov algorythm: kx,ky,kphi
# angle_distance: [7.0,2.0,0.3]              # parameter for angle distance algorythm: kl,kpsi,d  
angle_distance: [4.0,1.0,0.3]              # parameter for angle distance algorythm: kl,kpsi,d  
topic_current_odometry: "odometry/filtered"  #Source of state estamination
publish_tf: true  #Should be published at tf?
world_frame: "/map" #Name of the map frame
thresh: [0.0, 0.0, 0.0] #Thresholds for stopping motion. If velocities are below thresh the robot stops (Prevents oszillation)


#Formation member specification
master:      
  controller: 
    controller_type: 2
    reference: [1.0 ,1.0 , 0, 0 ,0 ,0 ]    #X Y Z R P Y given in the world frame
    topic_target_odometry:      "/trajectory_odom"  #Topic where the target position/velocities are given at

robot1:  
  controller:
    master: "master"
    reference: [1.0 , -1.0, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:       "/trajectory_odom" 

robot2:      
  controller:
    master: "master"
    reference: [-1.0 ,1.0, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:         "/trajectory_odom"    #topi  the target odometry of the robot is published at

robot3:
  controller:
    master: "master"
    reference: [-1.0,-1.0, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:         "/trajectory_odom"      #topi  the target odometry of the robot is published at

robot4:  
  controller:
    master: "master"
    reference: [-1.5, 1.5, 0, 0 ,0 ,0 ]    #X Y Z R P Y
    topic_target_odometry:         "/trajectory_odom"        

robot5:
  controller:
    master: "master"
    reference: [-1.5 , 0 , 0, 0 ,0 ,0 ]    #X Y Z R P Y
    publish_tf: true  
    topic_target_odometry:        "/trajectory_odom"     #topi  the target odometry of the robot is published at